apiVersion: apps/v1
kind: Deployment
metadata:
  name: meditation-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: meditation-app
  template:
    metadata:
      labels:
        app: meditation-app
    spec:
      containers:
      - name: meditation-app
        image: docker.io/zixiucsd/meditation-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "kubernetes"
        - name: DB_HOST
          value: "mysql-service"
        volumeMounts:
        - name: uploads
          mountPath: /usr/src/app/public/uploads
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc