name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      KUBECONFIG: ${{ github.workspace }}/kubeconfig
    
    steps:
      # Step 1: Check out your code
      - uses: actions/checkout@v3

      # Step 2: Set up the kubeconfig from your secret
      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > kubeconfig
          chmod 600 kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      # Step 3: Verify cluster access (optional but recommended)
      # This step checks if kubectl can reach your cluster
      - name: Verify cluster connection
        run: kubectl --kubeconfig ./kubeconfig get pods -A

      # Step 4: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/mysql-deployment.yaml
          kubectl apply -f k8s/mysql-service.yaml
          kubectl apply -f k8s/persistent-volumes.yaml
          kubectl apply -f k8s/app-deployment-prod.yaml
          kubectl apply -f k8s/app-service.yaml